# Generated by Django 4.2.14 on 2024-07-28 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiyasi', models.CharField(max_length=200)),
                ('ismi', models.CharField(max_length=200)),
                ('sharifi', models.CharField(max_length=200)),
                ('tugilgan_kuni', models.DateField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=300)),
                ('passport', models.CharField(max_length=150)),
                ('pinfl', models.PositiveBigIntegerField()),
                ('telefon_raqami', models.CharField(max_length=13)),
                ('tibbiy_brigada', models.PositiveBigIntegerField()),
                ('ovqatlanish_turi', models.CharField(choices=[("To'g'ri", "To'g'ri"), ("Noto'g'ri", "Noto'g'ri")], max_length=150)),
                ('jismoniy_faolligi', models.CharField(choices=[('Faol', 'Faol'), ('Nofaol', 'Nofaol')], max_length=150)),
                ('zararli_odat', models.CharField(choices=[('Mavjud', 'Mavjud'), ('Mavjud emas', 'Mavjud emas')], max_length=150)),
                ('vazn', models.IntegerField()),
                ('buy', models.IntegerField()),
                ('tvi', models.IntegerField()),
                ('tashhisi', models.TextField()),
                ('salomatlik_guruhi', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=150)),
                ('soglamlashtirish', models.CharField(choices=[('Ambulator', 'Ambulator'), ('Tuman', 'Tuman'), ('Viloyat', 'Viloyat'), ('Respublika', 'Respublika')], max_length=150)),
                ('muassasa_nomi', models.CharField(max_length=200)),
                ('davolash_chorak', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=150)),
                ('xatlov_sana', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
